### create an account (get accountId for the following requests)

POST {{serverUrl}}/api/v1/accounts
Content-Type: application/json

{
  "name": "johny"
}
### deposit funds

POST {{serverUrl}}/api/v1/accounts/{{accountId}}/actions
Content-Type: application/json

{
  "action": "deposit",
  "funds": 120
}

### create an offer (get offerId for the following requests)
POST {{serverUrl}}/api/v1/offers
Content-Type: application/json

{
  "name": "chocolate",
  "price": 100
}

### purchase an offer
POST {{serverUrl}}/api/v1/offers/{{offerId}}/actions
Content-Type: application/json

{
  "action": "purchase",
  "price": 100,
  "accountId": "{{accountId}}"
}

### check account
GET {{serverUrl}}/api/v1/accounts/{{accountId}}

### check offer
GET {{serverUrl}}/api/v1/offers/{{offerId}}